"""Entry point for the zipapp bundle built by ``tools/build_pyz.py``.

This file is the archive's ``__main__.py``: running ``python nobroker.pyz`` lands
here. It exists as a real file rather than being generated by ``zipapp -m`` so
that the CLI's **exit code is propagated** -- ``zipapp``'s generated stub calls
``main()`` and discards the return value, which would make every failure look
like a success to a shell.
"""

from __future__ import annotations

import sys

from nobroker.cli import main

if __name__ == "__main__":
    sys.exit(main())
